language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyouridea
  api_key:
    secure: fMf1C5Du33fpp9CgA9/CQYlQFCtHDl1tEaMndN8wAQV/Kc3lIoNnM0fARPONiknwvvDL+C/rMiu9VrunmBZgv/5DFz7L2Wqcvtu58XdjkcOxz7T+S07oIzGC6bjg4N/KaKJT493/9Tq7Lhan3dgehph/sa3z0sBrwFVpTPrVFLZprgdpldfpZiNUZy5AkmOBVaVvs+HK/qWXJwpzaPxUmEn/+T9mG0aXVfCjD0a+wRf4bvAkT28dBlm3voWrg5lPuLRIfj2kow3xyYujYjVM8z5Jf/jCsQM5uupSFLVqWMEk4qqhmEpzmtYgypxTBsW7eg4NwrF+NsPxFD0HX6p1okJpNtfLysGsIKvXbvacsvqSRmrIsLsUuv/wmwFjUTe9TiW9kltPM0ORdtVoc9L4jPuBxUkgnVmNnT3uQpaynm+l622ZFNipzFiRSG6kCQ2K5wFbYrRlUx/7TZsQLIKQ3ZBSmSulCQS4bouyCO5JIQp+zwBnvT2UaAmYpQTx574dofrc3tttRiV81bvBMZrBthGJVnXp3zTT2+ccYu+d8px35ZgWhIaXI6DcUzELICYzr9YuWAwRuj6YzVH7gK2j5yz+/wSgP1rNg3gkilFLt6/56+3WUZophevXUxLkAA+ghSRE5BOM/5JzP+C4w1XCPoVsxYmpttCEXejdh/AGtrI=
