version: "3"
services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/testing
      - APPLICATION_NAME="Share Your Idea",
      - JWT_SECRET= g49803mgf93m4f3f90234kf903r213rk2!!!
      - CACHE_KEY=myStrongPasswordKey
      - SWAGGER_DOC=swaggerDEV
    ports:
      - "3000:3000"
  mongo:
    image: mongo
